#!/bin/sh

<<authorsrightsnotice
        Author's Rights (C) Eqilia Luminé <eqilia@national.shitposting.agency>

        This file is licensed under the European Union Public License, version 1.2 only.
authorsrightsnotice

pkgname="musl"
pkgdesc="A C library that implements standards and widely accepted extensions"
pkgver="1.2.5"
pkgrel="0"
subpkgs="musl musl-devel"
pkgrdeps="none"
pkgbdeps="petpet-sdk"

pkgtb="https://musl.libc.org/releases/musl-$pkgver.tar.gz"

configure() {
        ./configure \
                --prefix=/usr \
                --libdir=/usr/lib/x86_64-musl
}

build() {
        make $MAKEOPTS
}

package() {
        make $MAKEOPTS install \
                DESTDIR="$bundledir"
}

package_musl() {
	pkgrdeps="none"

        petcp "usr/lib"
        petcp "/lib"
}

package_musl_devel() {
	pkgrdeps="none"

        petcp "usr/include"
}

