#!/bin/sh

pkgname="musl"
pkgver="1.2.5"
pkgrel="0"
subpkgs="musl musl-devel"
pkgrdeps="none"
pkgbdeps="petpet-sdk"

pkgtb="https://musl.libc.org/releases/musl-$pkgver.tar.gz"

configure() {
        ./configure \
                --prefix=/usr \
                --libdir=/usr/lib/x86_64-musl
}

build() {
        make $MAKEOPTS
}

package() {
        make $MAKEOPTS install \
                DESTDIR="$bundledir"
}

package_musl() {
        petcp "usr/lib"
        petcp "lib"
}

package_musl_devel() {
        petcp "usr/include"
}

