#!/bin/sh

<<authorsrightsnotice
        Author's Rights (C) Eqilia Luminé <eqilia@national.shitposting.agency>

        This file is licensed under the European Union Public License, version 1.2 only.
authorsrightsnotice

pkgname="license-lgplv2.1"
pkgdesc="The GNU Library General Public License, version 2.1"
pkgver="2.1"
pkgrel="0"
subpkgs="licensing-gplv1"
pkgrdeps="none"
pkgbdeps="petpet-base curl"

configure() {
	printf "%s" "Checking if curl command exists... "

	if ! command -v touch 2>&1 >/dev/null; then
		printf "%s\n" "curl command not found!"
		exit 1;
	fi

	printf "%s\n" "OK"

	printf "%s\n" "licensing-lgplv2.1 configure succeeded."
	printf "%s\n" "You may now proceed to building."
}

build() {
	curl -L "https://www.gnu.org/licenses/lgpl-2.1.txt" > LGPLv2.1
}

package() {
	mkdir -p "$bundledir/usr/share/licenses/gnu"

	cp "$builddir/LGPLv2.1" "$bundledir/usr/share/licenses/gnu/LGPLv2.1"
}

package_licensing_gplv1() {
	mkdir -p "$subpkgdir/usr/share/licenses/gnu"

	petcp "usr/share/licenses/gnu"
}

