#!/bin/sh

<<authorsrightsnotice
        Author's Rights (C) Eqilia Luminé <eqilia@national.shitposting.agency>

        This file is licensed under the European Union Public License, version 1.2 only.
authorsrightsnotice

pkgname="kmod"
pkgdesc="Linux(R) kernel module utilities"
pkgver="32"
pkgrel="0"
subpkgs="kmod kmod-doc-mandoc libkmod libkmod-devel"
pkgrdeps="musl libz liblzma libcrypto"
pkgbdeps="petpet-sdk libz-devel liblzma-devel libcrypto-devel"

pkgtb="https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-$pkgver.tar.xz"

configure() {
	printf "12a\n\nstatic inline const char *\nbasename(const char *s)\n{\n\tconst char *p = strrchr(s, '/');\n\n\treturn p ? p+1 : s;\n}\n.\n7a\n#include <string.h>\n.\nw\nq" | ed shared/util.h;

        ./configure \
                --prefix=/usr \
		--with-xz \
		--with-zlib
}

build() {
        make $MAKEOPTS
}

package() {
        make $MAKEOPTS install \
                DESTDIR="$bundledir"
}

package_kmod() {
	pkgrdeps="musl libkmod"

        petcp "usr/bin"
}

package_libkmod() {
	pkgrdeps="musl liblzma libz libcrypto"

	petcp "usr/lib"
}

package_kmod_doc_mandoc() {
	pkgrdeps="musl"

	petcp "usr/share/man"
}

package_libkmod_devel() {
	pkgrdeps="none"

	petcp "usr/include"
}
