#!/bin/sh

<<authorsrightsnotice
        Author's Rights (C) Eqilia Luminé <eqilia@national.shitposting.agency>

        This file is licensed under the European Union Public License, version 1.2 only.
authorsrightsnotice

pkgname="libmnl"
pkgver="1.0.5"
pkgrel="0"
subpkgs="libmnl libmnl-devel"
pkgrdeps="musl"
pkgbdeps="petpet-sdk linux-headers automake m4 autoconf perl"

pkgtb="https://www.netfilter.org/pub/libmnl/libmnl-$pkgver.tar.bz2"

configure() {
        ./configure \
                --prefix=/usr 
}

build() {
        make $MAKEOPTS
}

package() {
        make $MAKEOPTS install \
                DESTDIR="$bundledir"
}

package_libmnl() {
	pkgrdeps="musl"

        petcp "usr/lib"
}

package_libmnl_devel() {
	pkgrdeps="none"

        petcp "usr/include"
}

