#!/bin/sh

<<authorsrightsnotice
        Author's Rights (C) Eqilia Luminé <eqilia@national.shitposting.agency>

        This file is licensed under the European Union Public License, version 1.2 only.
authorsrightsnotice

pkgname="acl"
pkgdesc="Library and wrapper for access control lists"
pkgver="2.3.2"
pkgrel="0"
subpkgs="acl acl-devel acl-doc-mandoc acl-doc-notices"
pkgrdeps="musl"
pkgbdeps="petpet-sdk"

pkgtb="http://quantum-mirror.hu/mirrors/pub/gnusavannah/acl/acl-$pkgver.tar.xz"

configure() {
        ./configure \
                --prefix=/usr \
		--libdir=/lib
}

build() {
        make $MAKEOPTS
}

package() {
        make $MAKEOPTS install \
                DESTDIR="$bundledir"
}

package_acl() {
	pkgrdeps="musl"

        petcp "/lib"
}

package_acl_devel() {
	pkgrdeps="none"

	petcp "usr/include"
}

package_acl_doc_mandoc() {
	pkgrdeps="none"

        petcp "usr/share/man"
}

package_acl_doc_notices() {
	pkgrdeps="none"

	petcp "usr/share/doc"
}
