#!/bin/sh

<<authorsrightsnotice
        Author's Rights (C) Eqilia Luminé <eqilia@national.shitposting.agency>

        This file is licensed under the European Union Public License, version 1.2 only.
authorsrightsnotice

pkgname="fastfetch"
pkgdesc="System information in a fashionable way, written in C (and faster ^w^)"
pkgver="2.21.1"
pkgrel="0"
subpkgs="fastfetch fastfetch-doc-mandoc"
pkgrdeps="musl"
pkgbdeps="petpet-sdk cmake"

pkgtb="https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/$pkgver.tar.gz"

configure() {
	mkdir "build"
	cd "build"
	
	cmake ..
}

build() {
        make $MAKEOPTS
}

package() {
        make $MAKEOPTS install \
                DESTDIR="$bundledir"
}

package_fastfetch() {
	pkgrdeps="musl"

        petcp "usr/bin"
}

package_fastfetch_doc_mandoc() {
	pkgrdeps="none"

	petcp "usr/share/man"
	petcp "usr/share/licenses/fastfetch"
}

